### ISSUE TITLE
Send An Email To User Regarding Notification

### ISSUE THREAD

**Issue by Emon69420** [pranshukas/vaccine-info#3]
Send An Email When User chooses to be notified, eg- your notification is setup successfully

**Comment by pranshukas** [comment]
**When You Subscribe To our Services We display you this Sucess Page if Your Registration was Successful. This Page is an indication that your Registration was successful** 

![image](https://user-images.githubusercontent.com/58984074/119235419-104a1380-bb50-11eb-8fba-3c21d632d09d.png)

🙌 Thanks for Suggesting, We will also add this Feature for our Users in the future.
