### ISSUE TITLE
what is the use of .env file in the script??

### ISSUE THREAD

**Issue by Emon69420** [pranshukas/vaccine-info#4]

**Comment by pranshukas** [comment]
.env file is updated just to keep the email id and password in a separate file. You can remove that in case you don't want to use dotenv file. Although in case you want to use it make sure to rename the variable in the capital letters, for more reference you can see the dotenv documentation: https://www.npmjs.com/package/dotenv . 

In case you don't want to use it just remove the my-email-id and password variable and put actually emailid and password in the Sendmail function.
