### ISSUE TITLE
hosting this without node js

### ISSUE THREAD

**Issue by Emon69420** [pranshukas/Vaccine-Info#5]
if i want to host a particular part, not the whole website, on google cloud, can i skip the node js part?

**Comment by pranshukas** [comment]
Nodejs is used as a backend service mainly for checking available slots and send emails to users. In case you want to host the website on Google Cloud or some other hosting Platform you have to make some changes in case you want to remove nodejs dependencies. 
You have to use some scheduler for scheduling tasks, a package for sending emails, and call APIs to check slots from the server side.

**Comment by Emon69420** [comment]
Yes I was gonna use Google cloud,  and I will keep node JS but can I skip the part of local host?

**Comment by pranshukas** [comment]
Yes, you can skip the website hosting portion and use the code for Vaccine Availability Check. Use the functions and configure them according to yourself.

**Comment by pranshukas** [comment]
In case you're facing some difficulties, or any other issues, you can ping me at Linkedin/Insta/FB or Mail me I would try to help you in every possible way! 
Good Day!
